mybatis-plus:
  mapper-locations: classpath:com/lengmou/demo/mapper/xml/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://rm-8vbxeni7abaw8hoge58870.mysql.zhangbei.rds.aliyuncs.com:3306/demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: demo
    password: xiaoyuxin1996
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 10000
      timeBetweenEvictionRunsMillis: 300000
      validationQuery: select 1
  redis:
    host: 172.26.174.140
    port: 6379
    database: 0
    password: xiaoyuxin1996
